In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline  

import seaborn as sns

In [2]:
df_15= pd.read_csv('2015.csv', index_col= 'Country') # 158 rows, 12 cols  
# the happiness score is the sum of all the 7 columns after std error

df_16= pd.read_csv('2016.csv', index_col = 'Country')  # 157 rows, 13 col
df_17= pd.read_csv('2017.csv', index_col = 'Country')  # 155 x 11
df_18= pd.read_csv('2018.csv', index_col = 'Country or region')    # 156 x 12
df_19= pd.read_csv('2019.csv', index_col = 'Country or region')    # 156 x 8
df_20= pd.read_excel('2020.xls', index_col = 'Country name')   # 153 x 20

In [3]:
# Rename the columns as Factor+Year e.g. Economy2017, Generosity2020, ..

happyness_rank = ['Happiness Rank', 'Happiness Rank', 'Happiness.Rank',
                 'Overall rank', 'Overall rank', 'Happiness Rank']
happyness_score = ['Happiness Score', 'Happiness Score', 'Happiness.Score', 
                  'Score', 'Score', 'Ladder score']
economy = ['Economy (GDP per Capita)', 'Economy (GDP per Capita)',
          'Economy..GDP.per.Capita.', 'GDP per capita', 'GDP per capita',
          'Logged GDP per capita']
family = ['Family', 'Family', 'Family', 
          'Social Support', 'Social Support', 'Social Support']
health = ['Health (Life Expectancy)', 'Health (Life Expectancy)', 
         'Health..Life.Expectancy.', 'Healthy life expectancy', 
         'Healthy life expectancy', 'Healthy life expectancy']
freedom = ['Freedom', 'Freedom', 'Freedom', 
          'Freedom to make life choices', 'Freedom to make life choices', 
          'Freedom to make life choices']
trust = ['Trust (Government Corruption)', 'Trust (Government Corruption)',
         'Trust..Government.Corruption.', 'Perceptions of corruption',
         'Perceptions of corruption', 'Perceptions of corruption']
# Generosity is ok


df = [df_15, df_16, df_17, df_18, df_19, df_20]
factors = [happyness_rank, happyness_score,
    economy, family, health, freedom, trust, ['Generosity' for i in range(6)]]
names = ['Rank', 'Score', 'Economy', 'Family', 'Health', 'Freedom', 'Trust', 'Generosity']
for i in range(len(df)):
    cols= dict()
    for j in range(len(factors)):
        cols[factors[j][i]] = names[j]+str(2015+i)
    df[i].rename(columns = cols, inplace= True)

In [4]:
df_15

,Region,Rank2015,Score2015,Standard Error,Economy2015,Family2015,Health2015,Freedom2015,Trust2015,Generosity2015,Dystopia Residual
Country,,,,,,,,,,,
Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176
...,...,...,...,...,...,...,...,...,...,...,...
Rwanda,Sub-Saharan Africa,154,3.465,0.03464,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628,0.67042
Benin,Sub-Saharan Africa,155,3.340,0.03656,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260,1.63328
Syria,Middle East and Northern Africa,156,3.006,0.05015,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179,0.32858
Burundi,Sub-Saharan Africa,157,2.905,0.08658,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727,1.83302
Togo,Sub-Saharan Africa,158,2.839,0.06727,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681,1.56726

In [ ]:
# function that creates a dataframe with scores/family/economy/.. per year, indexed on country names
# name is the factor: Rank, Family, ...
def dataframe_years(name):
    df = df_15[[name+'2015']]
    df = df.join(df_16[[name+'2016']], how= 'outer')
    df = df.join(df_17[[name+'2017']], how= 'outer')
    df = df.join(df_18[[name+'2018']], how= 'outer')
    df = df.join(df_19[[name+'2019']], how= 'outer')
    df = df.join(df_20[[name+'2020']], how= 'outer')
    return df

In [ ]:
# scores:

scores = dataframe_years('Score')
scores.head()

In [ ]:
# Deal with NaNs

scores[scores.isnull().any(axis=1)]

In [ ]:
# Hong Kong <-- Hong Kong S.A.R., China
scores.loc['Hong Kong']['Score2017'] =  scores.loc['Hong Kong S.A.R., China']['Score2017']
scores.loc['Hong Kong']['Score2020'] =  scores.loc['Hong Kong S.A.R. of China']['Score2020']



# Taiwan <-- Taiwan Province of China
scores.loc['Taiwan']['Score2017'] =  scores.loc['Taiwan Province of China']['Score2017']

# Trinidad and Tobago <-- Trinidad & Tobago
scores.loc['Trinidad and Tobago']['Score2018'] =  scores.loc['Trinidad & Tobago']['Score2018']
scores.loc['Trinidad and Tobago']['Score2019'] =  scores.loc['Trinidad & Tobago']['Score2019']

# Northern Cyprus --> North Cyprus
scores.loc['North Cyprus']['Score2018'] =  scores.loc['Northern Cyprus']['Score2018']
scores.loc['North Cyprus']['Score2019'] =  scores.loc['Northern Cyprus']['Score2019']

# Somaliland Region <-- Somaliland region

scores.loc['Somaliland Region']['Score2015'] =  scores.loc['Somaliland region']['Score2015']

scores.drop(labels = ['Hong Kong S.A.R., China',
                      'Hong Kong S.A.R. of China',
                      'Taiwan Province of China',
                      'Trinidad & Tobago',
                      'Northern Cyprus',
                      'Somaliland region',
                     'Maldives'], 
            inplace= True)

In [ ]:
# Drop the remote ones with ranks only in one year
scores.drop(labels = ['Djibouti',
                      'Gambia',
                      'North Macedonia',
                      'Puerto Rico',
                      'Oman',
                      #'Swaziland',
                      #'Suriname',
                      #'Somaliland Region',
                      #'Belize',
                     ], 
            inplace= True)

In [ ]:
scores.loc['Angola']['Score2019'] =  3.795 # stabile in 2018 e 2017
scores.loc['Angola']['Score2020'] =  3.795 


scores.loc['Belize']['Score2015'] = 5.956 # son tutti uguali
scores.loc['Belize']['Score2019'] = 5.956
scores.loc['Belize']['Score2020'] = 5.956

scores.loc['Namibia']['Score2015'] = 4.574 # stabile in 2016 e 2017

scores.loc['Somaliland Region']['Score2017'] = 5.057 # son tutti uguali
scores.loc['Somaliland Region']['Score2018'] = 5.057
scores.loc['Somaliland Region']['Score2019'] = 5.057
scores.loc['Somaliland Region']['Score2020'] = 5.057

scores.loc['Sudan']['Score2019'] = 4.139
scores.loc['Sudan']['Score2020'] = 4.139

scores.loc['Suriname']['Score2017'] = 6.269 # son tutti uguali
scores.loc['Suriname']['Score2018'] = 6.269
scores.loc['Suriname']['Score2019'] = 6.269
scores.loc['Suriname']['Score2020'] = 6.269

scores.loc['Bhutan']['Score2020'] = 5.082

scores.loc['Qatar']['Score2020'] = 6.374

scores.loc['Syria']['Score2020'] = 3.462

In [ ]:
scores.rename(index = {'Somaliland Region': 'Somaliland'}, inplace=True)

In [ ]:
# fill the remaining with mean values of year before and after

scores.loc['Central African Republic']['Score2016'] = (3.678+2.693)/2
scores.loc['Comoros']['Score2017'] = (3.956+3.973)/2
scores.loc['Comoros']['Score2018'] = (3.956+3.973)/2
scores.loc['Laos']['Score2017'] = (4.876+4.623)/2
scores.loc['Lesotho']['Score2016'] = (4.898+3.808)/2
scores.loc['Macedonia']['Score2019'] = (5.185+5.1598)/2
scores.loc['Mozambique']['Score2016'] = (4.971+4.550)/2
scores.loc['Somalia']['Score2015'] = 5.440
scores.loc['Somalia']['Score2020'] = 4.668
scores.loc['South Sudan']['Score2015'] = 3.832
scores.loc['Swaziland']['Score2016'] = (4.867+4.212)/2
scores.loc['Swaziland']['Score2017'] = (4.867+4.212)/2
scores.loc['Swaziland']['Score2018'] = (4.867+4.212)/2
scores.loc['Taiwan']['Score2020'] = 6.446

# ----------------- end missing values of score

In [ ]:
# extract the csv for the happyness world map (see happyness_map.ipynb)

#scores.to_csv('Country.csv')

In [ ]:
# Let's study how happyness changed during the years

scores_delta = scores.copy()

for n in range(5):
    interval = str(15+n)+'-'+str(15+n+1)  # for ex. '15-16' in the first iteration
    scores_delta[interval] = scores_delta['Score'+str(2015+n+1)]-scores_delta['Score'+str(2015+n)] # scores of 2016 minus scores of 2015

scores_delta.drop(labels = ['Score2015',
                      'Score2016',
                      'Score2017',
                      'Score2018',
                      'Score2019',
                      'Score2020'], axis=1,
            inplace= True)
scores_delta.head()

In [ ]:
scores_delta.describe()
# looks like on average it decreased in the first two year, incrising afterwards

In [ ]:
# in case want to do some histogram based on the geographical area

region = {'Western Europe' : 'Europe', 
          'North America' : 'America', 
          'Australia and New Zealand' : 'Australia',
       'Middle East and Northern Africa' : 'Africa', 
          'Latin America and Caribbean' : 'America',
       'Southeastern Asia' : 'Asia', 
          'Central and Eastern Europe': 'Europe', 
          'Eastern Asia' : 'Asia',
       'Sub-Saharan Africa' : 'Africa', 
          'Southern Asia' : 'Asia'}
df_15['Continent'] = df_15.Region.replace(region)

In [ ]:
# plot how the rank changed in some european countries during the years
# notice how different they are!

years = ['15', '16', '17', '18', '19', '20']

fig, axs = plt.subplots(3, 3)
axs[0, 0].plot(years, scores.loc['Italy'])
axs[0, 0].set_title('Italy')
axs[0, 1].plot(years, scores.loc['France'])
axs[0, 1].set_title('France')
axs[0, 2].plot(years, scores.loc['Germany'])
axs[0, 2].set_title('Germany')
axs[1, 0].plot(years, scores.loc['Denmark'])
axs[1, 0].set_title('Denmark')
axs[1, 1].plot(years, scores.loc['Hungary'])
axs[1, 1].set_title('Hungary')
axs[1, 2].plot(years, scores.loc['Spain'])
axs[1, 2].set_title('Spain')
axs[2, 0].plot(years, scores.loc['United Kingdom'])
axs[2, 0].set_title('United Kingdom')
axs[2, 1].plot(years, scores.loc['Norway'])
axs[2, 1].set_title('Norway')
axs[2, 2].plot(years, scores.loc['Switzerland'])
axs[2, 2].set_title('Switzerland')

for ax in axs.flat:
    ax.label_outer()

In [ ]:
# democrazia o dittatura?
# source of the data: https://freedomhouse.org/report/freedom-world
file_name = 'Country_and_Territory_Ratings_and_Statuses_FIW1973-2021.xlsx'
politics = pd.read_excel(file_name,
                        sheet_name = 'Country Ratings, Statuses ',
                        header = [1,2],
                        index_col = 0)

In [ ]:
politic = politics[[2015,2016,2017,2018,2019,2020]].copy()
politic[2015][['Status']]
# F: Free, PF: Partly Free, NF: Non Free

In [ ]:
pol = []
for i in range(6):
    pol.append(scores[['Score'+str(2015+i)]].join(politic[2015+i][['Status']], how= 'left'))
    
# 2015: 
pol[0][pol[0].isnull().any(axis=1)]

In [ ]:
# fill the missibg values
miss_pol_15 = {'Hong Kong': 'PF', 
              'Ivory Coast': '',
              'Macedonia': '',
               'North Cyprus': '',
               'Palestinian Territories': '',
               'Somaliland': '',
               'Swaziland': '',
              }

In [ ]:
for i in range(6):
    print(pol[i].groupby(['Status']).mean(),'\n')
    print('Mean scores: ',pol[i]['Score'+str(2015+i)].mean())
    print('Median scores: ',pol[i]['Score'+str(2015+i)].median())